version: '3.8'

services:
  app:
    build: .
    container_name: go-around-home-task
    ports:
      - "3000:1989"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: go-around-home-task-postgress
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: mypassword123!
      POSTGRES_DB: around_home_task
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d/


